FROM apache/airflow:2.10.3

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY --chown=airflow:root pyproject.toml /opt/airflow/pyproject.toml
COPY --chown=airflow:root src/ /opt/airflow/src/
RUN pip install --no-cache-dir /opt/airflow